export const BingoLines = [
	[0, 1, 2, 3, 4],
	[5, 6, 7, 8, 9],
	[0, 5, 10, 15, 20],
	[1, 6, 11, 16, 21],
	[2, 7, 12, 17, 22],
	[3, 8, 13, 18, 23],
	[4, 9, 14, 19, 24],
	[0, 6, 12, 18, 24],
	[4, 8, 12, 16, 20],
	[10, 11, 12, 13, 14],
	[15, 16, 17, 18, 19],
	[20, 21, 22, 23, 24],
];
export const BingoCardTexts = [
	"What do you want to eat?",
	"Idk, you pick",
	"Up to you",
	"I'm not hungry",
	"What about you?",
	"What you want me to cook?",
	"You wanna eat outside?",
	"Let's order some food!",
	"Let's go grab something",
	"I'm down for anything",
	"Let's go outside and we'll figure it out on the road",
	"We just ate! When did you get hungry again?",
	"You wanna try something different today?",
	"You know I'm on a diet!",
	"I just want some coffee ☕️",
	"Naah, I'm okay",
	"I already ate outside",
	"We still got some leftovers from yesterday",
	"You think you can wait for an hour or so?",
	"Chicken and rice again? Really ? 😢",
	"You can't eat döner everyday! 😩",
	"Can we get ice cream? 🥺",
	"All I need is some dessert right now",
	"You got some space for dessert ?",
];
